spring:
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5432/bookshelf
    username: bookshelf
    password: bookshelf
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

application:
  title: '@project.name@'
  version: '@project.version@'
  credentials:
    admin:
      username: dbAdmin
      password: ${ADMIN_PASSWORD}
    user:
      username: dbUser
      password: ${USER_PASSWORD}

bookshelf:
  some-number: 11
  some-text: More information
  some-list:
    - First entry
    - Second entry
